### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory | RPI4 4Go Raspberry OS

### ISSUE THREAD

**Issue by gado070707** [nricheton/jeedom-docker-optimized#4]
Hello,
After launching the container :

```
version: "2.1"
services:
  jeedom:
    image: nricheton/jeedom-optimized:rpi-latest
    container_name: jeedom_serveur
    restart: unless-stopped
    hostname: jeedom
    network_mode: host
    volumes:
      - jeedom-html:/var/www/html
    environment:
      - APACHE_PORT=9080
      - ROOT_PASSWORD=azeAZE123123
    devices:
      - "/dev/ttyACM0:/dev/ttyUSB0"
      
volumes:
  jeedom-html:
```

, I get an error message telling me that the connection to mysql is impossible in http :
`
**SQLSTATE[HY000] [2002] No such file or directory**
`

## Log :
```
docker logs jeedom_serveur
Start init
Change apache listen port to : 9080
Change SSH listen port to : 9080
#       $OpenBSD: sshd_config,v 1.103 2018/04/09 20:41:22 tj Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# Expect .ssh/authorized_keys2 to be disregarded by default in future.
#AuthorizedKeysFile     .ssh/authorized_keys .ssh/authorized_keys2

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
ChallengeResponseAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin yes".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#TCPKeepAlive yes
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

# override default of no subsystems
Subsystem       sftp    /usr/lib/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#       X11Forwarding no
#       AllowTcpForwarding no
#       PermitTTY no
#       ForceCommand cvs server
Jeedom is already install
All init complete
Start apache2
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
AH00557: apache2: apr_sockaddr_info_get() failed for jeedom
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
Restarting Apache httpd web server: apache2.
Start sshd
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Restarting OpenBSD Secure Shell server: sshd.
Start atd
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Stopping deferred execution scheduler: atd.
Starting deferred execution scheduler: atd.
Change apache listen port to: 9080
Setup hostname to: jeedom
/usr/lib/python2.7/dist-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2021-10-06 11:30:27,665 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-10-06 11:30:27,665 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2021-10-06 11:30:27,744 INFO RPC interface 'supervisor' initialized
2021-10-06 11:30:27,745 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-10-06 11:30:27,745 INFO supervisord started with pid 83
2021-10-06 11:30:28,753 INFO spawned: 'cron' with pid 86
2021-10-06 11:30:29,757 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

The container mariadb :
```
version: "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb_serveur
    hostname: mariadb
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/peter/docker/mariadb/dossiers_de_configuration:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    
networks:
    backend:
        name: backend
        external: true
```

Do you have an idea ?

Thanks in advance.
