### ISSUE TITLE
[Erreur] Forbidden - You don't have permission to access this resource

### ISSUE THREAD

**Issue by Jason954** [nricheton/jeedom-docker-optimized#5]
Hello !

Je rencontre un souci lorsque j'essaye d'accéder à l'install de ton image : 

Forbidden
You don't have permission to access this resource.

J'ai juste transformé ton Docker Run en docker compose pour plus de facilité... Mais cela ne fonctionne pas non plus via docker run.

Voici mon docker compose : 

```
services:
  jeedom-server:
    image: nricheton/jeedom-optimized:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./jeedom-html:/var/www/html  
    environment:
      - APACHE_PORT=9080
      - ROOT_PASSWORD=password
  jeedom-mysql:
    image: mariadb:10.4
    container_name: jeedom-mysql
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password-root-sql
      - MYSQL_USER=jeedom
      - MYSQL_PASSWORD=password-jeedom-sql
      - MYSQL_DATABASE=jeedom
    ports:
      - "3306:3306"
```

Par avance, merci de ton aide!
